/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackOrderIdRouteImport } from './routes/track.$orderId'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppShiftsRouteImport } from './routes/app.shifts'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRecipesRouteImport } from './routes/app.recipes'
import { Route as AppPurchaseOrdersRouteImport } from './routes/app.purchase-orders'
import { Route as AppPromosRouteImport } from './routes/app.promos'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppPrintersRouteImport } from './routes/app.printers'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppOnlineOrdersRouteImport } from './routes/app.online-orders'
import { Route as AppMenuRouteImport } from './routes/app.menu'
import { Route as AppLoyaltyRouteImport } from './routes/app.loyalty'
import { Route as AppKdsRouteImport } from './routes/app.kds'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppDomainRouteImport } from './routes/app.domain'
import { Route as AppDeliveryRouteImport } from './routes/app.delivery'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppCouriersRouteImport } from './routes/app.couriers'
import { Route as AppCourierRouteImport } from './routes/app.courier'
import { Route as AppCategoriesRouteImport } from './routes/app.categories'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppBackupRouteImport } from './routes/app.backup'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAppearanceRouteImport } from './routes/app.appearance'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminDomainsRouteImport } from './routes/admin.domains'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminBroadcastRouteImport } from './routes/admin.broadcast'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as SSlugIndexRouteImport } from './routes/s.$slug.index'
import { Route as SSlugOrdersRouteImport } from './routes/s.$slug.orders'
import { Route as SSlugMeRouteImport } from './routes/s.$slug.me'
import { Route as SSlugLoginRouteImport } from './routes/s.$slug.login'
import { Route as SSlugCheckoutRouteImport } from './routes/s.$slug.checkout'
import { Route as SSlugCartRouteImport } from './routes/s.$slug.cart'
import { Route as AppPurchaseOrdersPoIdRouteImport } from './routes/app.purchase-orders.$poId'
import { Route as AdminShopsIdRouteImport } from './routes/admin.shops.$id'
import { Route as SSlugPayOrderIdRouteImport } from './routes/s.$slug.pay.$orderId'
import { Route as SSlugMenuMenuIdRouteImport } from './routes/s.$slug.menu.$menuId'
import { Route as AdminPlansIdMatrixRouteImport } from './routes/admin.plans.$id.matrix'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrackOrderIdRoute = TrackOrderIdRouteImport.update({
  id: '/track/$orderId',
  path: '/track/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPromosRoute = AppPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintersRoute = AppPrintersRouteImport.update({
  id: '/printers',
  path: '/printers',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppOnlineOrdersRoute = AppOnlineOrdersRouteImport.update({
  id: '/online-orders',
  path: '/online-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppLoyaltyRoute = AppLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AppRoute,
} as any)
const AppKdsRoute = AppKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainRoute = AppDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveryRoute = AppDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCouriersRoute = AppCouriersRouteImport.update({
  id: '/couriers',
  path: '/couriers',
  getParentRoute: () => AppRoute,
} as any)
const AppCourierRoute = AppCourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupRoute = AppBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAppearanceRoute = AppAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppRoute,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const SSlugIndexRoute = SSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugOrdersRoute = SSlugOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugMeRoute = SSlugMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugLoginRoute = SSlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugCheckoutRoute = SSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugCartRoute = SSlugCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SSlugRoute,
} as any)
const AppPurchaseOrdersPoIdRoute = AppPurchaseOrdersPoIdRouteImport.update({
  id: '/$poId',
  path: '/$poId',
  getParentRoute: () => AppPurchaseOrdersRoute,
} as any)
const AdminShopsIdRoute = AdminShopsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminShopsRoute,
} as any)
const SSlugPayOrderIdRoute = SSlugPayOrderIdRouteImport.update({
  id: '/pay/$orderId',
  path: '/pay/$orderId',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugMenuMenuIdRoute = SSlugMenuMenuIdRouteImport.update({
  id: '/menu/$menuId',
  path: '/menu/$menuId',
  getParentRoute: () => SSlugRoute,
} as any)
const AdminPlansIdMatrixRoute = AdminPlansIdMatrixRouteImport.update({
  id: '/$id/matrix',
  path: '/$id/matrix',
  getParentRoute: () => AdminPlansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/plans': typeof AdminPlansRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/app/appearance': typeof AppAppearanceRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/backup': typeof AppBackupRoute
  '/app/billing': typeof AppBillingRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/courier': typeof AppCourierRoute
  '/app/couriers': typeof AppCouriersRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/delivery': typeof AppDeliveryRoute
  '/app/domain': typeof AppDomainRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/kds': typeof AppKdsRoute
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/menu': typeof AppMenuRoute
  '/app/online-orders': typeof AppOnlineOrdersRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/pos': typeof AppPosRoute
  '/app/printers': typeof AppPrintersRoute
  '/app/promos': typeof AppPromosRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRouteWithChildren
  '/app/recipes': typeof AppRecipesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/track/$orderId': typeof TrackOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/shops/$id': typeof AdminShopsIdRoute
  '/app/purchase-orders/$poId': typeof AppPurchaseOrdersPoIdRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/login': typeof SSlugLoginRoute
  '/s/$slug/me': typeof SSlugMeRoute
  '/s/$slug/orders': typeof SSlugOrdersRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/admin/plans/$id/matrix': typeof AdminPlansIdMatrixRoute
  '/s/$slug/menu/$menuId': typeof SSlugMenuMenuIdRoute
  '/s/$slug/pay/$orderId': typeof SSlugPayOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/plans': typeof AdminPlansRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/app/appearance': typeof AppAppearanceRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/backup': typeof AppBackupRoute
  '/app/billing': typeof AppBillingRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/courier': typeof AppCourierRoute
  '/app/couriers': typeof AppCouriersRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/delivery': typeof AppDeliveryRoute
  '/app/domain': typeof AppDomainRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/kds': typeof AppKdsRoute
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/menu': typeof AppMenuRoute
  '/app/online-orders': typeof AppOnlineOrdersRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/pos': typeof AppPosRoute
  '/app/printers': typeof AppPrintersRoute
  '/app/promos': typeof AppPromosRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRouteWithChildren
  '/app/recipes': typeof AppRecipesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/shops/$id': typeof AdminShopsIdRoute
  '/app/purchase-orders/$poId': typeof AppPurchaseOrdersPoIdRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/login': typeof SSlugLoginRoute
  '/s/$slug/me': typeof SSlugMeRoute
  '/s/$slug/orders': typeof SSlugOrdersRoute
  '/s/$slug': typeof SSlugIndexRoute
  '/admin/plans/$id/matrix': typeof AdminPlansIdMatrixRoute
  '/s/$slug/menu/$menuId': typeof SSlugMenuMenuIdRoute
  '/s/$slug/pay/$orderId': typeof SSlugPayOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/plans': typeof AdminPlansRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/app/appearance': typeof AppAppearanceRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/backup': typeof AppBackupRoute
  '/app/billing': typeof AppBillingRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/courier': typeof AppCourierRoute
  '/app/couriers': typeof AppCouriersRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/delivery': typeof AppDeliveryRoute
  '/app/domain': typeof AppDomainRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/kds': typeof AppKdsRoute
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/menu': typeof AppMenuRoute
  '/app/online-orders': typeof AppOnlineOrdersRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/pos': typeof AppPosRoute
  '/app/printers': typeof AppPrintersRoute
  '/app/promos': typeof AppPromosRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRouteWithChildren
  '/app/recipes': typeof AppRecipesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/track/$orderId': typeof TrackOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/shops/$id': typeof AdminShopsIdRoute
  '/app/purchase-orders/$poId': typeof AppPurchaseOrdersPoIdRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/login': typeof SSlugLoginRoute
  '/s/$slug/me': typeof SSlugMeRoute
  '/s/$slug/orders': typeof SSlugOrdersRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/admin/plans/$id/matrix': typeof AdminPlansIdMatrixRoute
  '/s/$slug/menu/$menuId': typeof SSlugMenuMenuIdRoute
  '/s/$slug/pay/$orderId': typeof SSlugPayOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/activity'
    | '/admin/audit'
    | '/admin/broadcast'
    | '/admin/catalog'
    | '/admin/domains'
    | '/admin/invoices'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/shops'
    | '/app/appearance'
    | '/app/attendance'
    | '/app/backup'
    | '/app/billing'
    | '/app/categories'
    | '/app/courier'
    | '/app/couriers'
    | '/app/customers'
    | '/app/delivery'
    | '/app/domain'
    | '/app/employees'
    | '/app/inventory'
    | '/app/kds'
    | '/app/loyalty'
    | '/app/menu'
    | '/app/online-orders'
    | '/app/orders'
    | '/app/pos'
    | '/app/printers'
    | '/app/promos'
    | '/app/purchase-orders'
    | '/app/recipes'
    | '/app/reports'
    | '/app/schedule'
    | '/app/settings'
    | '/app/shifts'
    | '/app/suppliers'
    | '/invite/$token'
    | '/s/$slug'
    | '/track/$orderId'
    | '/admin/'
    | '/app/'
    | '/admin/shops/$id'
    | '/app/purchase-orders/$poId'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/login'
    | '/s/$slug/me'
    | '/s/$slug/orders'
    | '/s/$slug/'
    | '/admin/plans/$id/matrix'
    | '/s/$slug/menu/$menuId'
    | '/s/$slug/pay/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/activity'
    | '/admin/audit'
    | '/admin/broadcast'
    | '/admin/catalog'
    | '/admin/domains'
    | '/admin/invoices'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/shops'
    | '/app/appearance'
    | '/app/attendance'
    | '/app/backup'
    | '/app/billing'
    | '/app/categories'
    | '/app/courier'
    | '/app/couriers'
    | '/app/customers'
    | '/app/delivery'
    | '/app/domain'
    | '/app/employees'
    | '/app/inventory'
    | '/app/kds'
    | '/app/loyalty'
    | '/app/menu'
    | '/app/online-orders'
    | '/app/orders'
    | '/app/pos'
    | '/app/printers'
    | '/app/promos'
    | '/app/purchase-orders'
    | '/app/recipes'
    | '/app/reports'
    | '/app/schedule'
    | '/app/settings'
    | '/app/shifts'
    | '/app/suppliers'
    | '/invite/$token'
    | '/track/$orderId'
    | '/admin'
    | '/app'
    | '/admin/shops/$id'
    | '/app/purchase-orders/$poId'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/login'
    | '/s/$slug/me'
    | '/s/$slug/orders'
    | '/s/$slug'
    | '/admin/plans/$id/matrix'
    | '/s/$slug/menu/$menuId'
    | '/s/$slug/pay/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/activity'
    | '/admin/audit'
    | '/admin/broadcast'
    | '/admin/catalog'
    | '/admin/domains'
    | '/admin/invoices'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/shops'
    | '/app/appearance'
    | '/app/attendance'
    | '/app/backup'
    | '/app/billing'
    | '/app/categories'
    | '/app/courier'
    | '/app/couriers'
    | '/app/customers'
    | '/app/delivery'
    | '/app/domain'
    | '/app/employees'
    | '/app/inventory'
    | '/app/kds'
    | '/app/loyalty'
    | '/app/menu'
    | '/app/online-orders'
    | '/app/orders'
    | '/app/pos'
    | '/app/printers'
    | '/app/promos'
    | '/app/purchase-orders'
    | '/app/recipes'
    | '/app/reports'
    | '/app/schedule'
    | '/app/settings'
    | '/app/shifts'
    | '/app/suppliers'
    | '/invite/$token'
    | '/s/$slug'
    | '/track/$orderId'
    | '/admin/'
    | '/app/'
    | '/admin/shops/$id'
    | '/app/purchase-orders/$poId'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/login'
    | '/s/$slug/me'
    | '/s/$slug/orders'
    | '/s/$slug/'
    | '/admin/plans/$id/matrix'
    | '/s/$slug/menu/$menuId'
    | '/s/$slug/pay/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SSlugRoute: typeof SSlugRouteWithChildren
  TrackOrderIdRoute: typeof TrackOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/track/$orderId': {
      id: '/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/track/$orderId'
      preLoaderRoute: typeof TrackOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shifts': {
      id: '/app/shifts'
      path: '/shifts'
      fullPath: '/app/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recipes': {
      id: '/app/recipes'
      path: '/recipes'
      fullPath: '/app/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders': {
      id: '/app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/promos': {
      id: '/app/promos'
      path: '/promos'
      fullPath: '/app/promos'
      preLoaderRoute: typeof AppPromosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/printers': {
      id: '/app/printers'
      path: '/printers'
      fullPath: '/app/printers'
      preLoaderRoute: typeof AppPrintersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/online-orders': {
      id: '/app/online-orders'
      path: '/online-orders'
      fullPath: '/app/online-orders'
      preLoaderRoute: typeof AppOnlineOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/menu': {
      id: '/app/menu'
      path: '/menu'
      fullPath: '/app/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/loyalty': {
      id: '/app/loyalty'
      path: '/loyalty'
      fullPath: '/app/loyalty'
      preLoaderRoute: typeof AppLoyaltyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kds': {
      id: '/app/kds'
      path: '/kds'
      fullPath: '/app/kds'
      preLoaderRoute: typeof AppKdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/domain': {
      id: '/app/domain'
      path: '/domain'
      fullPath: '/app/domain'
      preLoaderRoute: typeof AppDomainRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/delivery': {
      id: '/app/delivery'
      path: '/delivery'
      fullPath: '/app/delivery'
      preLoaderRoute: typeof AppDeliveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/couriers': {
      id: '/app/couriers'
      path: '/couriers'
      fullPath: '/app/couriers'
      preLoaderRoute: typeof AppCouriersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courier': {
      id: '/app/courier'
      path: '/courier'
      fullPath: '/app/courier'
      preLoaderRoute: typeof AppCourierRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/backup': {
      id: '/app/backup'
      path: '/backup'
      fullPath: '/app/backup'
      preLoaderRoute: typeof AppBackupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appearance': {
      id: '/app/appearance'
      path: '/appearance'
      fullPath: '/app/appearance'
      preLoaderRoute: typeof AppAppearanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/domains': {
      id: '/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$slug/': {
      id: '/s/$slug/'
      path: '/'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof SSlugIndexRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/orders': {
      id: '/s/$slug/orders'
      path: '/orders'
      fullPath: '/s/$slug/orders'
      preLoaderRoute: typeof SSlugOrdersRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/me': {
      id: '/s/$slug/me'
      path: '/me'
      fullPath: '/s/$slug/me'
      preLoaderRoute: typeof SSlugMeRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/login': {
      id: '/s/$slug/login'
      path: '/login'
      fullPath: '/s/$slug/login'
      preLoaderRoute: typeof SSlugLoginRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/checkout': {
      id: '/s/$slug/checkout'
      path: '/checkout'
      fullPath: '/s/$slug/checkout'
      preLoaderRoute: typeof SSlugCheckoutRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/cart': {
      id: '/s/$slug/cart'
      path: '/cart'
      fullPath: '/s/$slug/cart'
      preLoaderRoute: typeof SSlugCartRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/app/purchase-orders/$poId': {
      id: '/app/purchase-orders/$poId'
      path: '/$poId'
      fullPath: '/app/purchase-orders/$poId'
      preLoaderRoute: typeof AppPurchaseOrdersPoIdRouteImport
      parentRoute: typeof AppPurchaseOrdersRoute
    }
    '/admin/shops/$id': {
      id: '/admin/shops/$id'
      path: '/$id'
      fullPath: '/admin/shops/$id'
      preLoaderRoute: typeof AdminShopsIdRouteImport
      parentRoute: typeof AdminShopsRoute
    }
    '/s/$slug/pay/$orderId': {
      id: '/s/$slug/pay/$orderId'
      path: '/pay/$orderId'
      fullPath: '/s/$slug/pay/$orderId'
      preLoaderRoute: typeof SSlugPayOrderIdRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/menu/$menuId': {
      id: '/s/$slug/menu/$menuId'
      path: '/menu/$menuId'
      fullPath: '/s/$slug/menu/$menuId'
      preLoaderRoute: typeof SSlugMenuMenuIdRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/admin/plans/$id/matrix': {
      id: '/admin/plans/$id/matrix'
      path: '/$id/matrix'
      fullPath: '/admin/plans/$id/matrix'
      preLoaderRoute: typeof AdminPlansIdMatrixRouteImport
      parentRoute: typeof AdminPlansRoute
    }
  }
}

interface AdminPlansRouteChildren {
  AdminPlansIdMatrixRoute: typeof AdminPlansIdMatrixRoute
}

const AdminPlansRouteChildren: AdminPlansRouteChildren = {
  AdminPlansIdMatrixRoute: AdminPlansIdMatrixRoute,
}

const AdminPlansRouteWithChildren = AdminPlansRoute._addFileChildren(
  AdminPlansRouteChildren,
)

interface AdminShopsRouteChildren {
  AdminShopsIdRoute: typeof AdminShopsIdRoute
}

const AdminShopsRouteChildren: AdminShopsRouteChildren = {
  AdminShopsIdRoute: AdminShopsIdRoute,
}

const AdminShopsRouteWithChildren = AdminShopsRoute._addFileChildren(
  AdminShopsRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminDomainsRoute: typeof AdminDomainsRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminPlansRoute: typeof AdminPlansRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShopsRoute: typeof AdminShopsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminDomainsRoute: AdminDomainsRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminPlansRoute: AdminPlansRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShopsRoute: AdminShopsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppPurchaseOrdersRouteChildren {
  AppPurchaseOrdersPoIdRoute: typeof AppPurchaseOrdersPoIdRoute
}

const AppPurchaseOrdersRouteChildren: AppPurchaseOrdersRouteChildren = {
  AppPurchaseOrdersPoIdRoute: AppPurchaseOrdersPoIdRoute,
}

const AppPurchaseOrdersRouteWithChildren =
  AppPurchaseOrdersRoute._addFileChildren(AppPurchaseOrdersRouteChildren)

interface AppRouteChildren {
  AppAppearanceRoute: typeof AppAppearanceRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBackupRoute: typeof AppBackupRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCourierRoute: typeof AppCourierRoute
  AppCouriersRoute: typeof AppCouriersRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDeliveryRoute: typeof AppDeliveryRoute
  AppDomainRoute: typeof AppDomainRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppKdsRoute: typeof AppKdsRoute
  AppLoyaltyRoute: typeof AppLoyaltyRoute
  AppMenuRoute: typeof AppMenuRoute
  AppOnlineOrdersRoute: typeof AppOnlineOrdersRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPosRoute: typeof AppPosRoute
  AppPrintersRoute: typeof AppPrintersRoute
  AppPromosRoute: typeof AppPromosRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRouteWithChildren
  AppRecipesRoute: typeof AppRecipesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShiftsRoute: typeof AppShiftsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppearanceRoute: AppAppearanceRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBackupRoute: AppBackupRoute,
  AppBillingRoute: AppBillingRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCourierRoute: AppCourierRoute,
  AppCouriersRoute: AppCouriersRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDeliveryRoute: AppDeliveryRoute,
  AppDomainRoute: AppDomainRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppKdsRoute: AppKdsRoute,
  AppLoyaltyRoute: AppLoyaltyRoute,
  AppMenuRoute: AppMenuRoute,
  AppOnlineOrdersRoute: AppOnlineOrdersRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPosRoute: AppPosRoute,
  AppPrintersRoute: AppPrintersRoute,
  AppPromosRoute: AppPromosRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRouteWithChildren,
  AppRecipesRoute: AppRecipesRoute,
  AppReportsRoute: AppReportsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShiftsRoute: AppShiftsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SSlugRouteChildren {
  SSlugCartRoute: typeof SSlugCartRoute
  SSlugCheckoutRoute: typeof SSlugCheckoutRoute
  SSlugLoginRoute: typeof SSlugLoginRoute
  SSlugMeRoute: typeof SSlugMeRoute
  SSlugOrdersRoute: typeof SSlugOrdersRoute
  SSlugIndexRoute: typeof SSlugIndexRoute
  SSlugMenuMenuIdRoute: typeof SSlugMenuMenuIdRoute
  SSlugPayOrderIdRoute: typeof SSlugPayOrderIdRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugCartRoute: SSlugCartRoute,
  SSlugCheckoutRoute: SSlugCheckoutRoute,
  SSlugLoginRoute: SSlugLoginRoute,
  SSlugMeRoute: SSlugMeRoute,
  SSlugOrdersRoute: SSlugOrdersRoute,
  SSlugIndexRoute: SSlugIndexRoute,
  SSlugMenuMenuIdRoute: SSlugMenuMenuIdRoute,
  SSlugPayOrderIdRoute: SSlugPayOrderIdRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  SSlugRoute: SSlugRouteWithChildren,
  TrackOrderIdRoute: TrackOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

// Server-side router registration removed for client-only Vite build
