/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as PosAppRouteImport } from './routes/pos-app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AkunRouteImport } from './routes/akun'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosAppIndexRouteImport } from './routes/pos-app.index'
import { Route as KategoriIndexRouteImport } from './routes/kategori.index'
import { Route as AkunIndexRouteImport } from './routes/akun.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackOrderIdRouteImport } from './routes/track.$orderId'
import { Route as TokoSlugRouteImport } from './routes/toko.$slug'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as PosAppTablesRouteImport } from './routes/pos-app.tables'
import { Route as PosAppTableMapsRouteImport } from './routes/pos-app.table-maps'
import { Route as PosAppSuppliersRouteImport } from './routes/pos-app.suppliers'
import { Route as PosAppShiftsRouteImport } from './routes/pos-app.shifts'
import { Route as PosAppSettingsRouteImport } from './routes/pos-app.settings'
import { Route as PosAppScheduleRouteImport } from './routes/pos-app.schedule'
import { Route as PosAppReviewsRouteImport } from './routes/pos-app.reviews'
import { Route as PosAppReportsRouteImport } from './routes/pos-app.reports'
import { Route as PosAppRecipesRouteImport } from './routes/pos-app.recipes'
import { Route as PosAppPurchaseOrdersRouteImport } from './routes/pos-app.purchase-orders'
import { Route as PosAppPromosRouteImport } from './routes/pos-app.promos'
import { Route as PosAppPrintersRouteImport } from './routes/pos-app.printers'
import { Route as PosAppPosRouteImport } from './routes/pos-app.pos'
import { Route as PosAppOrdersRouteImport } from './routes/pos-app.orders'
import { Route as PosAppOnlineOrdersRouteImport } from './routes/pos-app.online-orders'
import { Route as PosAppMenuRouteImport } from './routes/pos-app.menu'
import { Route as PosAppMarketplaceOrdersRouteImport } from './routes/pos-app.marketplace-orders'
import { Route as PosAppLoyaltyRouteImport } from './routes/pos-app.loyalty'
import { Route as PosAppKeuanganRouteImport } from './routes/pos-app.keuangan'
import { Route as PosAppKdsRouteImport } from './routes/pos-app.kds'
import { Route as PosAppInventoryRouteImport } from './routes/pos-app.inventory'
import { Route as PosAppEmployeesRouteImport } from './routes/pos-app.employees'
import { Route as PosAppDomainRouteImport } from './routes/pos-app.domain'
import { Route as PosAppDeliveryRouteImport } from './routes/pos-app.delivery'
import { Route as PosAppCustomersRouteImport } from './routes/pos-app.customers'
import { Route as PosAppCouriersRouteImport } from './routes/pos-app.couriers'
import { Route as PosAppCourierRouteImport } from './routes/pos-app.courier'
import { Route as PosAppCategoriesRouteImport } from './routes/pos-app.categories'
import { Route as PosAppBillingRouteImport } from './routes/pos-app.billing'
import { Route as PosAppBackupRouteImport } from './routes/pos-app.backup'
import { Route as PosAppAttendanceRouteImport } from './routes/pos-app.attendance'
import { Route as PosAppAppearanceRouteImport } from './routes/pos-app.appearance'
import { Route as PesananOrderIdRouteImport } from './routes/pesanan.$orderId'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AkunAlamatRouteImport } from './routes/akun.alamat'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminVouchersRouteImport } from './routes/admin.vouchers'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminDomainsRouteImport } from './routes/admin.domains'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminBroadcastRouteImport } from './routes/admin.broadcast'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as SSlugIndexRouteImport } from './routes/s.$slug.index'
import { Route as AkunPesananIndexRouteImport } from './routes/akun.pesanan.index'
import { Route as SSlugOrdersRouteImport } from './routes/s.$slug.orders'
import { Route as SSlugMeRouteImport } from './routes/s.$slug.me'
import { Route as SSlugLoginRouteImport } from './routes/s.$slug.login'
import { Route as SSlugCheckoutRouteImport } from './routes/s.$slug.checkout'
import { Route as SSlugCartRouteImport } from './routes/s.$slug.cart'
import { Route as PosAppReportsProfitRouteImport } from './routes/pos-app.reports.profit'
import { Route as PosAppPurchaseOrdersPoIdRouteImport } from './routes/pos-app.purchase-orders.$poId'
import { Route as PosAppKeuanganTarikRouteImport } from './routes/pos-app.keuangan.tarik'
import { Route as CheckoutSuksesOrderIdRouteImport } from './routes/checkout.sukses.$orderId'
import { Route as AkunPesananOrderIdRouteImport } from './routes/akun.pesanan.$orderId'
import { Route as AdminShopsIdRouteImport } from './routes/admin.shops.$id'
import { Route as TokoSlugProdukProductIdRouteImport } from './routes/toko.$slug.produk.$productId'
import { Route as SSlugPayOrderIdRouteImport } from './routes/s.$slug.pay.$orderId'
import { Route as SSlugMenuMenuIdRouteImport } from './routes/s.$slug.menu.$menuId'
import { Route as AdminPlansIdMatrixRouteImport } from './routes/admin.plans.$id.matrix'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const PosAppRoute = PosAppRouteImport.update({
  id: '/pos-app',
  path: '/pos-app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunRoute = AkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosAppIndexRoute = PosAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PosAppRoute,
} as any)
const KategoriIndexRoute = KategoriIndexRouteImport.update({
  id: '/kategori/',
  path: '/kategori/',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunIndexRoute = AkunIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AkunRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrackOrderIdRoute = TrackOrderIdRouteImport.update({
  id: '/track/$orderId',
  path: '/track/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const TokoSlugRoute = TokoSlugRouteImport.update({
  id: '/toko/$slug',
  path: '/toko/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PosAppTablesRoute = PosAppTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppTableMapsRoute = PosAppTableMapsRouteImport.update({
  id: '/table-maps',
  path: '/table-maps',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppSuppliersRoute = PosAppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppShiftsRoute = PosAppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppSettingsRoute = PosAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppScheduleRoute = PosAppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppReviewsRoute = PosAppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppReportsRoute = PosAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppRecipesRoute = PosAppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppPurchaseOrdersRoute = PosAppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppPromosRoute = PosAppPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppPrintersRoute = PosAppPrintersRouteImport.update({
  id: '/printers',
  path: '/printers',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppPosRoute = PosAppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppOrdersRoute = PosAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppOnlineOrdersRoute = PosAppOnlineOrdersRouteImport.update({
  id: '/online-orders',
  path: '/online-orders',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppMenuRoute = PosAppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppMarketplaceOrdersRoute = PosAppMarketplaceOrdersRouteImport.update({
  id: '/marketplace-orders',
  path: '/marketplace-orders',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppLoyaltyRoute = PosAppLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppKeuanganRoute = PosAppKeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppKdsRoute = PosAppKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppInventoryRoute = PosAppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppEmployeesRoute = PosAppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppDomainRoute = PosAppDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppDeliveryRoute = PosAppDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppCustomersRoute = PosAppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppCouriersRoute = PosAppCouriersRouteImport.update({
  id: '/couriers',
  path: '/couriers',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppCourierRoute = PosAppCourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppCategoriesRoute = PosAppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppBillingRoute = PosAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppBackupRoute = PosAppBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppAttendanceRoute = PosAppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => PosAppRoute,
} as any)
const PosAppAppearanceRoute = PosAppAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => PosAppRoute,
} as any)
const PesananOrderIdRoute = PesananOrderIdRouteImport.update({
  id: '/pesanan/$orderId',
  path: '/pesanan/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunAlamatRoute = AkunAlamatRouteImport.update({
  id: '/alamat',
  path: '/alamat',
  getParentRoute: () => AkunRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVouchersRoute = AdminVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const SSlugIndexRoute = SSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SSlugRoute,
} as any)
const AkunPesananIndexRoute = AkunPesananIndexRouteImport.update({
  id: '/pesanan/',
  path: '/pesanan/',
  getParentRoute: () => AkunRoute,
} as any)
const SSlugOrdersRoute = SSlugOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugMeRoute = SSlugMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugLoginRoute = SSlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugCheckoutRoute = SSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugCartRoute = SSlugCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SSlugRoute,
} as any)
const PosAppReportsProfitRoute = PosAppReportsProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => PosAppReportsRoute,
} as any)
const PosAppPurchaseOrdersPoIdRoute =
  PosAppPurchaseOrdersPoIdRouteImport.update({
    id: '/$poId',
    path: '/$poId',
    getParentRoute: () => PosAppPurchaseOrdersRoute,
  } as any)
const PosAppKeuanganTarikRoute = PosAppKeuanganTarikRouteImport.update({
  id: '/tarik',
  path: '/tarik',
  getParentRoute: () => PosAppKeuanganRoute,
} as any)
const CheckoutSuksesOrderIdRoute = CheckoutSuksesOrderIdRouteImport.update({
  id: '/sukses/$orderId',
  path: '/sukses/$orderId',
  getParentRoute: () => CheckoutRoute,
} as any)
const AkunPesananOrderIdRoute = AkunPesananOrderIdRouteImport.update({
  id: '/pesanan/$orderId',
  path: '/pesanan/$orderId',
  getParentRoute: () => AkunRoute,
} as any)
const AdminShopsIdRoute = AdminShopsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminShopsRoute,
} as any)
const TokoSlugProdukProductIdRoute = TokoSlugProdukProductIdRouteImport.update({
  id: '/produk/$productId',
  path: '/produk/$productId',
  getParentRoute: () => TokoSlugRoute,
} as any)
const SSlugPayOrderIdRoute = SSlugPayOrderIdRouteImport.update({
  id: '/pay/$orderId',
  path: '/pay/$orderId',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugMenuMenuIdRoute = SSlugMenuMenuIdRouteImport.update({
  id: '/menu/$menuId',
  path: '/menu/$menuId',
  getParentRoute: () => SSlugRoute,
} as any)
const AdminPlansIdMatrixRoute = AdminPlansIdMatrixRouteImport.update({
  id: '/$id/matrix',
  path: '/$id/matrix',
  getParentRoute: () => AdminPlansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/akun': typeof AkunRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/keranjang': typeof KeranjangRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pos-app': typeof PosAppRouteWithChildren
  '/promo': typeof PromoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/plans': typeof AdminPlansRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/admin/vouchers': typeof AdminVouchersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/akun/alamat': typeof AkunAlamatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/pesanan/$orderId': typeof PesananOrderIdRoute
  '/pos-app/appearance': typeof PosAppAppearanceRoute
  '/pos-app/attendance': typeof PosAppAttendanceRoute
  '/pos-app/backup': typeof PosAppBackupRoute
  '/pos-app/billing': typeof PosAppBillingRoute
  '/pos-app/categories': typeof PosAppCategoriesRoute
  '/pos-app/courier': typeof PosAppCourierRoute
  '/pos-app/couriers': typeof PosAppCouriersRoute
  '/pos-app/customers': typeof PosAppCustomersRoute
  '/pos-app/delivery': typeof PosAppDeliveryRoute
  '/pos-app/domain': typeof PosAppDomainRoute
  '/pos-app/employees': typeof PosAppEmployeesRoute
  '/pos-app/inventory': typeof PosAppInventoryRoute
  '/pos-app/kds': typeof PosAppKdsRoute
  '/pos-app/keuangan': typeof PosAppKeuanganRouteWithChildren
  '/pos-app/loyalty': typeof PosAppLoyaltyRoute
  '/pos-app/marketplace-orders': typeof PosAppMarketplaceOrdersRoute
  '/pos-app/menu': typeof PosAppMenuRoute
  '/pos-app/online-orders': typeof PosAppOnlineOrdersRoute
  '/pos-app/orders': typeof PosAppOrdersRoute
  '/pos-app/pos': typeof PosAppPosRoute
  '/pos-app/printers': typeof PosAppPrintersRoute
  '/pos-app/promos': typeof PosAppPromosRoute
  '/pos-app/purchase-orders': typeof PosAppPurchaseOrdersRouteWithChildren
  '/pos-app/recipes': typeof PosAppRecipesRoute
  '/pos-app/reports': typeof PosAppReportsRouteWithChildren
  '/pos-app/reviews': typeof PosAppReviewsRoute
  '/pos-app/schedule': typeof PosAppScheduleRoute
  '/pos-app/settings': typeof PosAppSettingsRoute
  '/pos-app/shifts': typeof PosAppShiftsRoute
  '/pos-app/suppliers': typeof PosAppSuppliersRoute
  '/pos-app/table-maps': typeof PosAppTableMapsRoute
  '/pos-app/tables': typeof PosAppTablesRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/toko/$slug': typeof TokoSlugRouteWithChildren
  '/track/$orderId': typeof TrackOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/akun/': typeof AkunIndexRoute
  '/kategori/': typeof KategoriIndexRoute
  '/pos-app/': typeof PosAppIndexRoute
  '/admin/shops/$id': typeof AdminShopsIdRoute
  '/akun/pesanan/$orderId': typeof AkunPesananOrderIdRoute
  '/checkout/sukses/$orderId': typeof CheckoutSuksesOrderIdRoute
  '/pos-app/keuangan/tarik': typeof PosAppKeuanganTarikRoute
  '/pos-app/purchase-orders/$poId': typeof PosAppPurchaseOrdersPoIdRoute
  '/pos-app/reports/profit': typeof PosAppReportsProfitRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/login': typeof SSlugLoginRoute
  '/s/$slug/me': typeof SSlugMeRoute
  '/s/$slug/orders': typeof SSlugOrdersRoute
  '/akun/pesanan/': typeof AkunPesananIndexRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/admin/plans/$id/matrix': typeof AdminPlansIdMatrixRoute
  '/s/$slug/menu/$menuId': typeof SSlugMenuMenuIdRoute
  '/s/$slug/pay/$orderId': typeof SSlugPayOrderIdRoute
  '/toko/$slug/produk/$productId': typeof TokoSlugProdukProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/keranjang': typeof KeranjangRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/promo': typeof PromoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/plans': typeof AdminPlansRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/admin/vouchers': typeof AdminVouchersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/akun/alamat': typeof AkunAlamatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/pesanan/$orderId': typeof PesananOrderIdRoute
  '/pos-app/appearance': typeof PosAppAppearanceRoute
  '/pos-app/attendance': typeof PosAppAttendanceRoute
  '/pos-app/backup': typeof PosAppBackupRoute
  '/pos-app/billing': typeof PosAppBillingRoute
  '/pos-app/categories': typeof PosAppCategoriesRoute
  '/pos-app/courier': typeof PosAppCourierRoute
  '/pos-app/couriers': typeof PosAppCouriersRoute
  '/pos-app/customers': typeof PosAppCustomersRoute
  '/pos-app/delivery': typeof PosAppDeliveryRoute
  '/pos-app/domain': typeof PosAppDomainRoute
  '/pos-app/employees': typeof PosAppEmployeesRoute
  '/pos-app/inventory': typeof PosAppInventoryRoute
  '/pos-app/kds': typeof PosAppKdsRoute
  '/pos-app/keuangan': typeof PosAppKeuanganRouteWithChildren
  '/pos-app/loyalty': typeof PosAppLoyaltyRoute
  '/pos-app/marketplace-orders': typeof PosAppMarketplaceOrdersRoute
  '/pos-app/menu': typeof PosAppMenuRoute
  '/pos-app/online-orders': typeof PosAppOnlineOrdersRoute
  '/pos-app/orders': typeof PosAppOrdersRoute
  '/pos-app/pos': typeof PosAppPosRoute
  '/pos-app/printers': typeof PosAppPrintersRoute
  '/pos-app/promos': typeof PosAppPromosRoute
  '/pos-app/purchase-orders': typeof PosAppPurchaseOrdersRouteWithChildren
  '/pos-app/recipes': typeof PosAppRecipesRoute
  '/pos-app/reports': typeof PosAppReportsRouteWithChildren
  '/pos-app/reviews': typeof PosAppReviewsRoute
  '/pos-app/schedule': typeof PosAppScheduleRoute
  '/pos-app/settings': typeof PosAppSettingsRoute
  '/pos-app/shifts': typeof PosAppShiftsRoute
  '/pos-app/suppliers': typeof PosAppSuppliersRoute
  '/pos-app/table-maps': typeof PosAppTableMapsRoute
  '/pos-app/tables': typeof PosAppTablesRoute
  '/toko/$slug': typeof TokoSlugRouteWithChildren
  '/track/$orderId': typeof TrackOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/akun': typeof AkunIndexRoute
  '/kategori': typeof KategoriIndexRoute
  '/pos-app': typeof PosAppIndexRoute
  '/admin/shops/$id': typeof AdminShopsIdRoute
  '/akun/pesanan/$orderId': typeof AkunPesananOrderIdRoute
  '/checkout/sukses/$orderId': typeof CheckoutSuksesOrderIdRoute
  '/pos-app/keuangan/tarik': typeof PosAppKeuanganTarikRoute
  '/pos-app/purchase-orders/$poId': typeof PosAppPurchaseOrdersPoIdRoute
  '/pos-app/reports/profit': typeof PosAppReportsProfitRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/login': typeof SSlugLoginRoute
  '/s/$slug/me': typeof SSlugMeRoute
  '/s/$slug/orders': typeof SSlugOrdersRoute
  '/akun/pesanan': typeof AkunPesananIndexRoute
  '/s/$slug': typeof SSlugIndexRoute
  '/admin/plans/$id/matrix': typeof AdminPlansIdMatrixRoute
  '/s/$slug/menu/$menuId': typeof SSlugMenuMenuIdRoute
  '/s/$slug/pay/$orderId': typeof SSlugPayOrderIdRoute
  '/toko/$slug/produk/$productId': typeof TokoSlugProdukProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/akun': typeof AkunRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/keranjang': typeof KeranjangRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pos-app': typeof PosAppRouteWithChildren
  '/promo': typeof PromoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/plans': typeof AdminPlansRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shops': typeof AdminShopsRouteWithChildren
  '/admin/vouchers': typeof AdminVouchersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/akun/alamat': typeof AkunAlamatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/pesanan/$orderId': typeof PesananOrderIdRoute
  '/pos-app/appearance': typeof PosAppAppearanceRoute
  '/pos-app/attendance': typeof PosAppAttendanceRoute
  '/pos-app/backup': typeof PosAppBackupRoute
  '/pos-app/billing': typeof PosAppBillingRoute
  '/pos-app/categories': typeof PosAppCategoriesRoute
  '/pos-app/courier': typeof PosAppCourierRoute
  '/pos-app/couriers': typeof PosAppCouriersRoute
  '/pos-app/customers': typeof PosAppCustomersRoute
  '/pos-app/delivery': typeof PosAppDeliveryRoute
  '/pos-app/domain': typeof PosAppDomainRoute
  '/pos-app/employees': typeof PosAppEmployeesRoute
  '/pos-app/inventory': typeof PosAppInventoryRoute
  '/pos-app/kds': typeof PosAppKdsRoute
  '/pos-app/keuangan': typeof PosAppKeuanganRouteWithChildren
  '/pos-app/loyalty': typeof PosAppLoyaltyRoute
  '/pos-app/marketplace-orders': typeof PosAppMarketplaceOrdersRoute
  '/pos-app/menu': typeof PosAppMenuRoute
  '/pos-app/online-orders': typeof PosAppOnlineOrdersRoute
  '/pos-app/orders': typeof PosAppOrdersRoute
  '/pos-app/pos': typeof PosAppPosRoute
  '/pos-app/printers': typeof PosAppPrintersRoute
  '/pos-app/promos': typeof PosAppPromosRoute
  '/pos-app/purchase-orders': typeof PosAppPurchaseOrdersRouteWithChildren
  '/pos-app/recipes': typeof PosAppRecipesRoute
  '/pos-app/reports': typeof PosAppReportsRouteWithChildren
  '/pos-app/reviews': typeof PosAppReviewsRoute
  '/pos-app/schedule': typeof PosAppScheduleRoute
  '/pos-app/settings': typeof PosAppSettingsRoute
  '/pos-app/shifts': typeof PosAppShiftsRoute
  '/pos-app/suppliers': typeof PosAppSuppliersRoute
  '/pos-app/table-maps': typeof PosAppTableMapsRoute
  '/pos-app/tables': typeof PosAppTablesRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/toko/$slug': typeof TokoSlugRouteWithChildren
  '/track/$orderId': typeof TrackOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/akun/': typeof AkunIndexRoute
  '/kategori/': typeof KategoriIndexRoute
  '/pos-app/': typeof PosAppIndexRoute
  '/admin/shops/$id': typeof AdminShopsIdRoute
  '/akun/pesanan/$orderId': typeof AkunPesananOrderIdRoute
  '/checkout/sukses/$orderId': typeof CheckoutSuksesOrderIdRoute
  '/pos-app/keuangan/tarik': typeof PosAppKeuanganTarikRoute
  '/pos-app/purchase-orders/$poId': typeof PosAppPurchaseOrdersPoIdRoute
  '/pos-app/reports/profit': typeof PosAppReportsProfitRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/login': typeof SSlugLoginRoute
  '/s/$slug/me': typeof SSlugMeRoute
  '/s/$slug/orders': typeof SSlugOrdersRoute
  '/akun/pesanan/': typeof AkunPesananIndexRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/admin/plans/$id/matrix': typeof AdminPlansIdMatrixRoute
  '/s/$slug/menu/$menuId': typeof SSlugMenuMenuIdRoute
  '/s/$slug/pay/$orderId': typeof SSlugPayOrderIdRoute
  '/toko/$slug/produk/$productId': typeof TokoSlugProdukProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/akun'
    | '/checkout'
    | '/forgot-password'
    | '/keranjang'
    | '/login'
    | '/onboarding'
    | '/pos-app'
    | '/promo'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/broadcast'
    | '/admin/catalog'
    | '/admin/disputes'
    | '/admin/domains'
    | '/admin/invoices'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/shops'
    | '/admin/vouchers'
    | '/admin/withdrawals'
    | '/akun/alamat'
    | '/invite/$token'
    | '/kategori/$slug'
    | '/pesanan/$orderId'
    | '/pos-app/appearance'
    | '/pos-app/attendance'
    | '/pos-app/backup'
    | '/pos-app/billing'
    | '/pos-app/categories'
    | '/pos-app/courier'
    | '/pos-app/couriers'
    | '/pos-app/customers'
    | '/pos-app/delivery'
    | '/pos-app/domain'
    | '/pos-app/employees'
    | '/pos-app/inventory'
    | '/pos-app/kds'
    | '/pos-app/keuangan'
    | '/pos-app/loyalty'
    | '/pos-app/marketplace-orders'
    | '/pos-app/menu'
    | '/pos-app/online-orders'
    | '/pos-app/orders'
    | '/pos-app/pos'
    | '/pos-app/printers'
    | '/pos-app/promos'
    | '/pos-app/purchase-orders'
    | '/pos-app/recipes'
    | '/pos-app/reports'
    | '/pos-app/reviews'
    | '/pos-app/schedule'
    | '/pos-app/settings'
    | '/pos-app/shifts'
    | '/pos-app/suppliers'
    | '/pos-app/table-maps'
    | '/pos-app/tables'
    | '/s/$slug'
    | '/toko/$slug'
    | '/track/$orderId'
    | '/admin/'
    | '/akun/'
    | '/kategori/'
    | '/pos-app/'
    | '/admin/shops/$id'
    | '/akun/pesanan/$orderId'
    | '/checkout/sukses/$orderId'
    | '/pos-app/keuangan/tarik'
    | '/pos-app/purchase-orders/$poId'
    | '/pos-app/reports/profit'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/login'
    | '/s/$slug/me'
    | '/s/$slug/orders'
    | '/akun/pesanan/'
    | '/s/$slug/'
    | '/admin/plans/$id/matrix'
    | '/s/$slug/menu/$menuId'
    | '/s/$slug/pay/$orderId'
    | '/toko/$slug/produk/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/forgot-password'
    | '/keranjang'
    | '/login'
    | '/onboarding'
    | '/promo'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/broadcast'
    | '/admin/catalog'
    | '/admin/disputes'
    | '/admin/domains'
    | '/admin/invoices'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/shops'
    | '/admin/vouchers'
    | '/admin/withdrawals'
    | '/akun/alamat'
    | '/invite/$token'
    | '/kategori/$slug'
    | '/pesanan/$orderId'
    | '/pos-app/appearance'
    | '/pos-app/attendance'
    | '/pos-app/backup'
    | '/pos-app/billing'
    | '/pos-app/categories'
    | '/pos-app/courier'
    | '/pos-app/couriers'
    | '/pos-app/customers'
    | '/pos-app/delivery'
    | '/pos-app/domain'
    | '/pos-app/employees'
    | '/pos-app/inventory'
    | '/pos-app/kds'
    | '/pos-app/keuangan'
    | '/pos-app/loyalty'
    | '/pos-app/marketplace-orders'
    | '/pos-app/menu'
    | '/pos-app/online-orders'
    | '/pos-app/orders'
    | '/pos-app/pos'
    | '/pos-app/printers'
    | '/pos-app/promos'
    | '/pos-app/purchase-orders'
    | '/pos-app/recipes'
    | '/pos-app/reports'
    | '/pos-app/reviews'
    | '/pos-app/schedule'
    | '/pos-app/settings'
    | '/pos-app/shifts'
    | '/pos-app/suppliers'
    | '/pos-app/table-maps'
    | '/pos-app/tables'
    | '/toko/$slug'
    | '/track/$orderId'
    | '/admin'
    | '/akun'
    | '/kategori'
    | '/pos-app'
    | '/admin/shops/$id'
    | '/akun/pesanan/$orderId'
    | '/checkout/sukses/$orderId'
    | '/pos-app/keuangan/tarik'
    | '/pos-app/purchase-orders/$poId'
    | '/pos-app/reports/profit'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/login'
    | '/s/$slug/me'
    | '/s/$slug/orders'
    | '/akun/pesanan'
    | '/s/$slug'
    | '/admin/plans/$id/matrix'
    | '/s/$slug/menu/$menuId'
    | '/s/$slug/pay/$orderId'
    | '/toko/$slug/produk/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/akun'
    | '/checkout'
    | '/forgot-password'
    | '/keranjang'
    | '/login'
    | '/onboarding'
    | '/pos-app'
    | '/promo'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/broadcast'
    | '/admin/catalog'
    | '/admin/disputes'
    | '/admin/domains'
    | '/admin/invoices'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/shops'
    | '/admin/vouchers'
    | '/admin/withdrawals'
    | '/akun/alamat'
    | '/invite/$token'
    | '/kategori/$slug'
    | '/pesanan/$orderId'
    | '/pos-app/appearance'
    | '/pos-app/attendance'
    | '/pos-app/backup'
    | '/pos-app/billing'
    | '/pos-app/categories'
    | '/pos-app/courier'
    | '/pos-app/couriers'
    | '/pos-app/customers'
    | '/pos-app/delivery'
    | '/pos-app/domain'
    | '/pos-app/employees'
    | '/pos-app/inventory'
    | '/pos-app/kds'
    | '/pos-app/keuangan'
    | '/pos-app/loyalty'
    | '/pos-app/marketplace-orders'
    | '/pos-app/menu'
    | '/pos-app/online-orders'
    | '/pos-app/orders'
    | '/pos-app/pos'
    | '/pos-app/printers'
    | '/pos-app/promos'
    | '/pos-app/purchase-orders'
    | '/pos-app/recipes'
    | '/pos-app/reports'
    | '/pos-app/reviews'
    | '/pos-app/schedule'
    | '/pos-app/settings'
    | '/pos-app/shifts'
    | '/pos-app/suppliers'
    | '/pos-app/table-maps'
    | '/pos-app/tables'
    | '/s/$slug'
    | '/toko/$slug'
    | '/track/$orderId'
    | '/admin/'
    | '/akun/'
    | '/kategori/'
    | '/pos-app/'
    | '/admin/shops/$id'
    | '/akun/pesanan/$orderId'
    | '/checkout/sukses/$orderId'
    | '/pos-app/keuangan/tarik'
    | '/pos-app/purchase-orders/$poId'
    | '/pos-app/reports/profit'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/login'
    | '/s/$slug/me'
    | '/s/$slug/orders'
    | '/akun/pesanan/'
    | '/s/$slug/'
    | '/admin/plans/$id/matrix'
    | '/s/$slug/menu/$menuId'
    | '/s/$slug/pay/$orderId'
    | '/toko/$slug/produk/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AkunRoute: typeof AkunRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KeranjangRoute: typeof KeranjangRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PosAppRoute: typeof PosAppRouteWithChildren
  PromoRoute: typeof PromoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  PesananOrderIdRoute: typeof PesananOrderIdRoute
  SSlugRoute: typeof SSlugRouteWithChildren
  TokoSlugRoute: typeof TokoSlugRouteWithChildren
  TrackOrderIdRoute: typeof TrackOrderIdRoute
  KategoriIndexRoute: typeof KategoriIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-app': {
      id: '/pos-app'
      path: '/pos-app'
      fullPath: '/pos-app'
      preLoaderRoute: typeof PosAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun': {
      id: '/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AkunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-app/': {
      id: '/pos-app/'
      path: '/'
      fullPath: '/pos-app/'
      preLoaderRoute: typeof PosAppIndexRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/kategori/': {
      id: '/kategori/'
      path: '/kategori'
      fullPath: '/kategori/'
      preLoaderRoute: typeof KategoriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun/': {
      id: '/akun/'
      path: '/'
      fullPath: '/akun/'
      preLoaderRoute: typeof AkunIndexRouteImport
      parentRoute: typeof AkunRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/track/$orderId': {
      id: '/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/track/$orderId'
      preLoaderRoute: typeof TrackOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toko/$slug': {
      id: '/toko/$slug'
      path: '/toko/$slug'
      fullPath: '/toko/$slug'
      preLoaderRoute: typeof TokoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-app/tables': {
      id: '/pos-app/tables'
      path: '/tables'
      fullPath: '/pos-app/tables'
      preLoaderRoute: typeof PosAppTablesRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/table-maps': {
      id: '/pos-app/table-maps'
      path: '/table-maps'
      fullPath: '/pos-app/table-maps'
      preLoaderRoute: typeof PosAppTableMapsRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/suppliers': {
      id: '/pos-app/suppliers'
      path: '/suppliers'
      fullPath: '/pos-app/suppliers'
      preLoaderRoute: typeof PosAppSuppliersRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/shifts': {
      id: '/pos-app/shifts'
      path: '/shifts'
      fullPath: '/pos-app/shifts'
      preLoaderRoute: typeof PosAppShiftsRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/settings': {
      id: '/pos-app/settings'
      path: '/settings'
      fullPath: '/pos-app/settings'
      preLoaderRoute: typeof PosAppSettingsRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/schedule': {
      id: '/pos-app/schedule'
      path: '/schedule'
      fullPath: '/pos-app/schedule'
      preLoaderRoute: typeof PosAppScheduleRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/reviews': {
      id: '/pos-app/reviews'
      path: '/reviews'
      fullPath: '/pos-app/reviews'
      preLoaderRoute: typeof PosAppReviewsRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/reports': {
      id: '/pos-app/reports'
      path: '/reports'
      fullPath: '/pos-app/reports'
      preLoaderRoute: typeof PosAppReportsRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/recipes': {
      id: '/pos-app/recipes'
      path: '/recipes'
      fullPath: '/pos-app/recipes'
      preLoaderRoute: typeof PosAppRecipesRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/purchase-orders': {
      id: '/pos-app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/pos-app/purchase-orders'
      preLoaderRoute: typeof PosAppPurchaseOrdersRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/promos': {
      id: '/pos-app/promos'
      path: '/promos'
      fullPath: '/pos-app/promos'
      preLoaderRoute: typeof PosAppPromosRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/printers': {
      id: '/pos-app/printers'
      path: '/printers'
      fullPath: '/pos-app/printers'
      preLoaderRoute: typeof PosAppPrintersRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/pos': {
      id: '/pos-app/pos'
      path: '/pos'
      fullPath: '/pos-app/pos'
      preLoaderRoute: typeof PosAppPosRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/orders': {
      id: '/pos-app/orders'
      path: '/orders'
      fullPath: '/pos-app/orders'
      preLoaderRoute: typeof PosAppOrdersRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/online-orders': {
      id: '/pos-app/online-orders'
      path: '/online-orders'
      fullPath: '/pos-app/online-orders'
      preLoaderRoute: typeof PosAppOnlineOrdersRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/menu': {
      id: '/pos-app/menu'
      path: '/menu'
      fullPath: '/pos-app/menu'
      preLoaderRoute: typeof PosAppMenuRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/marketplace-orders': {
      id: '/pos-app/marketplace-orders'
      path: '/marketplace-orders'
      fullPath: '/pos-app/marketplace-orders'
      preLoaderRoute: typeof PosAppMarketplaceOrdersRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/loyalty': {
      id: '/pos-app/loyalty'
      path: '/loyalty'
      fullPath: '/pos-app/loyalty'
      preLoaderRoute: typeof PosAppLoyaltyRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/keuangan': {
      id: '/pos-app/keuangan'
      path: '/keuangan'
      fullPath: '/pos-app/keuangan'
      preLoaderRoute: typeof PosAppKeuanganRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/kds': {
      id: '/pos-app/kds'
      path: '/kds'
      fullPath: '/pos-app/kds'
      preLoaderRoute: typeof PosAppKdsRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/inventory': {
      id: '/pos-app/inventory'
      path: '/inventory'
      fullPath: '/pos-app/inventory'
      preLoaderRoute: typeof PosAppInventoryRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/employees': {
      id: '/pos-app/employees'
      path: '/employees'
      fullPath: '/pos-app/employees'
      preLoaderRoute: typeof PosAppEmployeesRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/domain': {
      id: '/pos-app/domain'
      path: '/domain'
      fullPath: '/pos-app/domain'
      preLoaderRoute: typeof PosAppDomainRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/delivery': {
      id: '/pos-app/delivery'
      path: '/delivery'
      fullPath: '/pos-app/delivery'
      preLoaderRoute: typeof PosAppDeliveryRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/customers': {
      id: '/pos-app/customers'
      path: '/customers'
      fullPath: '/pos-app/customers'
      preLoaderRoute: typeof PosAppCustomersRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/couriers': {
      id: '/pos-app/couriers'
      path: '/couriers'
      fullPath: '/pos-app/couriers'
      preLoaderRoute: typeof PosAppCouriersRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/courier': {
      id: '/pos-app/courier'
      path: '/courier'
      fullPath: '/pos-app/courier'
      preLoaderRoute: typeof PosAppCourierRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/categories': {
      id: '/pos-app/categories'
      path: '/categories'
      fullPath: '/pos-app/categories'
      preLoaderRoute: typeof PosAppCategoriesRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/billing': {
      id: '/pos-app/billing'
      path: '/billing'
      fullPath: '/pos-app/billing'
      preLoaderRoute: typeof PosAppBillingRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/backup': {
      id: '/pos-app/backup'
      path: '/backup'
      fullPath: '/pos-app/backup'
      preLoaderRoute: typeof PosAppBackupRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/attendance': {
      id: '/pos-app/attendance'
      path: '/attendance'
      fullPath: '/pos-app/attendance'
      preLoaderRoute: typeof PosAppAttendanceRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pos-app/appearance': {
      id: '/pos-app/appearance'
      path: '/appearance'
      fullPath: '/pos-app/appearance'
      preLoaderRoute: typeof PosAppAppearanceRouteImport
      parentRoute: typeof PosAppRoute
    }
    '/pesanan/$orderId': {
      id: '/pesanan/$orderId'
      path: '/pesanan/$orderId'
      fullPath: '/pesanan/$orderId'
      preLoaderRoute: typeof PesananOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun/alamat': {
      id: '/akun/alamat'
      path: '/alamat'
      fullPath: '/akun/alamat'
      preLoaderRoute: typeof AkunAlamatRouteImport
      parentRoute: typeof AkunRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vouchers': {
      id: '/admin/vouchers'
      path: '/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminVouchersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/domains': {
      id: '/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$slug/': {
      id: '/s/$slug/'
      path: '/'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof SSlugIndexRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/akun/pesanan/': {
      id: '/akun/pesanan/'
      path: '/pesanan'
      fullPath: '/akun/pesanan/'
      preLoaderRoute: typeof AkunPesananIndexRouteImport
      parentRoute: typeof AkunRoute
    }
    '/s/$slug/orders': {
      id: '/s/$slug/orders'
      path: '/orders'
      fullPath: '/s/$slug/orders'
      preLoaderRoute: typeof SSlugOrdersRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/me': {
      id: '/s/$slug/me'
      path: '/me'
      fullPath: '/s/$slug/me'
      preLoaderRoute: typeof SSlugMeRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/login': {
      id: '/s/$slug/login'
      path: '/login'
      fullPath: '/s/$slug/login'
      preLoaderRoute: typeof SSlugLoginRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/checkout': {
      id: '/s/$slug/checkout'
      path: '/checkout'
      fullPath: '/s/$slug/checkout'
      preLoaderRoute: typeof SSlugCheckoutRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/cart': {
      id: '/s/$slug/cart'
      path: '/cart'
      fullPath: '/s/$slug/cart'
      preLoaderRoute: typeof SSlugCartRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/pos-app/reports/profit': {
      id: '/pos-app/reports/profit'
      path: '/profit'
      fullPath: '/pos-app/reports/profit'
      preLoaderRoute: typeof PosAppReportsProfitRouteImport
      parentRoute: typeof PosAppReportsRoute
    }
    '/pos-app/purchase-orders/$poId': {
      id: '/pos-app/purchase-orders/$poId'
      path: '/$poId'
      fullPath: '/pos-app/purchase-orders/$poId'
      preLoaderRoute: typeof PosAppPurchaseOrdersPoIdRouteImport
      parentRoute: typeof PosAppPurchaseOrdersRoute
    }
    '/pos-app/keuangan/tarik': {
      id: '/pos-app/keuangan/tarik'
      path: '/tarik'
      fullPath: '/pos-app/keuangan/tarik'
      preLoaderRoute: typeof PosAppKeuanganTarikRouteImport
      parentRoute: typeof PosAppKeuanganRoute
    }
    '/checkout/sukses/$orderId': {
      id: '/checkout/sukses/$orderId'
      path: '/sukses/$orderId'
      fullPath: '/checkout/sukses/$orderId'
      preLoaderRoute: typeof CheckoutSuksesOrderIdRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/akun/pesanan/$orderId': {
      id: '/akun/pesanan/$orderId'
      path: '/pesanan/$orderId'
      fullPath: '/akun/pesanan/$orderId'
      preLoaderRoute: typeof AkunPesananOrderIdRouteImport
      parentRoute: typeof AkunRoute
    }
    '/admin/shops/$id': {
      id: '/admin/shops/$id'
      path: '/$id'
      fullPath: '/admin/shops/$id'
      preLoaderRoute: typeof AdminShopsIdRouteImport
      parentRoute: typeof AdminShopsRoute
    }
    '/toko/$slug/produk/$productId': {
      id: '/toko/$slug/produk/$productId'
      path: '/produk/$productId'
      fullPath: '/toko/$slug/produk/$productId'
      preLoaderRoute: typeof TokoSlugProdukProductIdRouteImport
      parentRoute: typeof TokoSlugRoute
    }
    '/s/$slug/pay/$orderId': {
      id: '/s/$slug/pay/$orderId'
      path: '/pay/$orderId'
      fullPath: '/s/$slug/pay/$orderId'
      preLoaderRoute: typeof SSlugPayOrderIdRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/menu/$menuId': {
      id: '/s/$slug/menu/$menuId'
      path: '/menu/$menuId'
      fullPath: '/s/$slug/menu/$menuId'
      preLoaderRoute: typeof SSlugMenuMenuIdRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/admin/plans/$id/matrix': {
      id: '/admin/plans/$id/matrix'
      path: '/$id/matrix'
      fullPath: '/admin/plans/$id/matrix'
      preLoaderRoute: typeof AdminPlansIdMatrixRouteImport
      parentRoute: typeof AdminPlansRoute
    }
  }
}

interface AdminPlansRouteChildren {
  AdminPlansIdMatrixRoute: typeof AdminPlansIdMatrixRoute
}

const AdminPlansRouteChildren: AdminPlansRouteChildren = {
  AdminPlansIdMatrixRoute: AdminPlansIdMatrixRoute,
}

const AdminPlansRouteWithChildren = AdminPlansRoute._addFileChildren(
  AdminPlansRouteChildren,
)

interface AdminShopsRouteChildren {
  AdminShopsIdRoute: typeof AdminShopsIdRoute
}

const AdminShopsRouteChildren: AdminShopsRouteChildren = {
  AdminShopsIdRoute: AdminShopsIdRoute,
}

const AdminShopsRouteWithChildren = AdminShopsRoute._addFileChildren(
  AdminShopsRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminDomainsRoute: typeof AdminDomainsRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminPlansRoute: typeof AdminPlansRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShopsRoute: typeof AdminShopsRouteWithChildren
  AdminVouchersRoute: typeof AdminVouchersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminDomainsRoute: AdminDomainsRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminPlansRoute: AdminPlansRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShopsRoute: AdminShopsRouteWithChildren,
  AdminVouchersRoute: AdminVouchersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AkunRouteChildren {
  AkunAlamatRoute: typeof AkunAlamatRoute
  AkunIndexRoute: typeof AkunIndexRoute
  AkunPesananOrderIdRoute: typeof AkunPesananOrderIdRoute
  AkunPesananIndexRoute: typeof AkunPesananIndexRoute
}

const AkunRouteChildren: AkunRouteChildren = {
  AkunAlamatRoute: AkunAlamatRoute,
  AkunIndexRoute: AkunIndexRoute,
  AkunPesananOrderIdRoute: AkunPesananOrderIdRoute,
  AkunPesananIndexRoute: AkunPesananIndexRoute,
}

const AkunRouteWithChildren = AkunRoute._addFileChildren(AkunRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSuksesOrderIdRoute: typeof CheckoutSuksesOrderIdRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuksesOrderIdRoute: CheckoutSuksesOrderIdRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface PosAppKeuanganRouteChildren {
  PosAppKeuanganTarikRoute: typeof PosAppKeuanganTarikRoute
}

const PosAppKeuanganRouteChildren: PosAppKeuanganRouteChildren = {
  PosAppKeuanganTarikRoute: PosAppKeuanganTarikRoute,
}

const PosAppKeuanganRouteWithChildren = PosAppKeuanganRoute._addFileChildren(
  PosAppKeuanganRouteChildren,
)

interface PosAppPurchaseOrdersRouteChildren {
  PosAppPurchaseOrdersPoIdRoute: typeof PosAppPurchaseOrdersPoIdRoute
}

const PosAppPurchaseOrdersRouteChildren: PosAppPurchaseOrdersRouteChildren = {
  PosAppPurchaseOrdersPoIdRoute: PosAppPurchaseOrdersPoIdRoute,
}

const PosAppPurchaseOrdersRouteWithChildren =
  PosAppPurchaseOrdersRoute._addFileChildren(PosAppPurchaseOrdersRouteChildren)

interface PosAppReportsRouteChildren {
  PosAppReportsProfitRoute: typeof PosAppReportsProfitRoute
}

const PosAppReportsRouteChildren: PosAppReportsRouteChildren = {
  PosAppReportsProfitRoute: PosAppReportsProfitRoute,
}

const PosAppReportsRouteWithChildren = PosAppReportsRoute._addFileChildren(
  PosAppReportsRouteChildren,
)

interface PosAppRouteChildren {
  PosAppAppearanceRoute: typeof PosAppAppearanceRoute
  PosAppAttendanceRoute: typeof PosAppAttendanceRoute
  PosAppBackupRoute: typeof PosAppBackupRoute
  PosAppBillingRoute: typeof PosAppBillingRoute
  PosAppCategoriesRoute: typeof PosAppCategoriesRoute
  PosAppCourierRoute: typeof PosAppCourierRoute
  PosAppCouriersRoute: typeof PosAppCouriersRoute
  PosAppCustomersRoute: typeof PosAppCustomersRoute
  PosAppDeliveryRoute: typeof PosAppDeliveryRoute
  PosAppDomainRoute: typeof PosAppDomainRoute
  PosAppEmployeesRoute: typeof PosAppEmployeesRoute
  PosAppInventoryRoute: typeof PosAppInventoryRoute
  PosAppKdsRoute: typeof PosAppKdsRoute
  PosAppKeuanganRoute: typeof PosAppKeuanganRouteWithChildren
  PosAppLoyaltyRoute: typeof PosAppLoyaltyRoute
  PosAppMarketplaceOrdersRoute: typeof PosAppMarketplaceOrdersRoute
  PosAppMenuRoute: typeof PosAppMenuRoute
  PosAppOnlineOrdersRoute: typeof PosAppOnlineOrdersRoute
  PosAppOrdersRoute: typeof PosAppOrdersRoute
  PosAppPosRoute: typeof PosAppPosRoute
  PosAppPrintersRoute: typeof PosAppPrintersRoute
  PosAppPromosRoute: typeof PosAppPromosRoute
  PosAppPurchaseOrdersRoute: typeof PosAppPurchaseOrdersRouteWithChildren
  PosAppRecipesRoute: typeof PosAppRecipesRoute
  PosAppReportsRoute: typeof PosAppReportsRouteWithChildren
  PosAppReviewsRoute: typeof PosAppReviewsRoute
  PosAppScheduleRoute: typeof PosAppScheduleRoute
  PosAppSettingsRoute: typeof PosAppSettingsRoute
  PosAppShiftsRoute: typeof PosAppShiftsRoute
  PosAppSuppliersRoute: typeof PosAppSuppliersRoute
  PosAppTableMapsRoute: typeof PosAppTableMapsRoute
  PosAppTablesRoute: typeof PosAppTablesRoute
  PosAppIndexRoute: typeof PosAppIndexRoute
}

const PosAppRouteChildren: PosAppRouteChildren = {
  PosAppAppearanceRoute: PosAppAppearanceRoute,
  PosAppAttendanceRoute: PosAppAttendanceRoute,
  PosAppBackupRoute: PosAppBackupRoute,
  PosAppBillingRoute: PosAppBillingRoute,
  PosAppCategoriesRoute: PosAppCategoriesRoute,
  PosAppCourierRoute: PosAppCourierRoute,
  PosAppCouriersRoute: PosAppCouriersRoute,
  PosAppCustomersRoute: PosAppCustomersRoute,
  PosAppDeliveryRoute: PosAppDeliveryRoute,
  PosAppDomainRoute: PosAppDomainRoute,
  PosAppEmployeesRoute: PosAppEmployeesRoute,
  PosAppInventoryRoute: PosAppInventoryRoute,
  PosAppKdsRoute: PosAppKdsRoute,
  PosAppKeuanganRoute: PosAppKeuanganRouteWithChildren,
  PosAppLoyaltyRoute: PosAppLoyaltyRoute,
  PosAppMarketplaceOrdersRoute: PosAppMarketplaceOrdersRoute,
  PosAppMenuRoute: PosAppMenuRoute,
  PosAppOnlineOrdersRoute: PosAppOnlineOrdersRoute,
  PosAppOrdersRoute: PosAppOrdersRoute,
  PosAppPosRoute: PosAppPosRoute,
  PosAppPrintersRoute: PosAppPrintersRoute,
  PosAppPromosRoute: PosAppPromosRoute,
  PosAppPurchaseOrdersRoute: PosAppPurchaseOrdersRouteWithChildren,
  PosAppRecipesRoute: PosAppRecipesRoute,
  PosAppReportsRoute: PosAppReportsRouteWithChildren,
  PosAppReviewsRoute: PosAppReviewsRoute,
  PosAppScheduleRoute: PosAppScheduleRoute,
  PosAppSettingsRoute: PosAppSettingsRoute,
  PosAppShiftsRoute: PosAppShiftsRoute,
  PosAppSuppliersRoute: PosAppSuppliersRoute,
  PosAppTableMapsRoute: PosAppTableMapsRoute,
  PosAppTablesRoute: PosAppTablesRoute,
  PosAppIndexRoute: PosAppIndexRoute,
}

const PosAppRouteWithChildren =
  PosAppRoute._addFileChildren(PosAppRouteChildren)

interface SSlugRouteChildren {
  SSlugCartRoute: typeof SSlugCartRoute
  SSlugCheckoutRoute: typeof SSlugCheckoutRoute
  SSlugLoginRoute: typeof SSlugLoginRoute
  SSlugMeRoute: typeof SSlugMeRoute
  SSlugOrdersRoute: typeof SSlugOrdersRoute
  SSlugIndexRoute: typeof SSlugIndexRoute
  SSlugMenuMenuIdRoute: typeof SSlugMenuMenuIdRoute
  SSlugPayOrderIdRoute: typeof SSlugPayOrderIdRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugCartRoute: SSlugCartRoute,
  SSlugCheckoutRoute: SSlugCheckoutRoute,
  SSlugLoginRoute: SSlugLoginRoute,
  SSlugMeRoute: SSlugMeRoute,
  SSlugOrdersRoute: SSlugOrdersRoute,
  SSlugIndexRoute: SSlugIndexRoute,
  SSlugMenuMenuIdRoute: SSlugMenuMenuIdRoute,
  SSlugPayOrderIdRoute: SSlugPayOrderIdRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

interface TokoSlugRouteChildren {
  TokoSlugProdukProductIdRoute: typeof TokoSlugProdukProductIdRoute
}

const TokoSlugRouteChildren: TokoSlugRouteChildren = {
  TokoSlugProdukProductIdRoute: TokoSlugProdukProductIdRoute,
}

const TokoSlugRouteWithChildren = TokoSlugRoute._addFileChildren(
  TokoSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AkunRoute: AkunRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KeranjangRoute: KeranjangRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PosAppRoute: PosAppRouteWithChildren,
  PromoRoute: PromoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  PesananOrderIdRoute: PesananOrderIdRoute,
  SSlugRoute: SSlugRouteWithChildren,
  TokoSlugRoute: TokoSlugRouteWithChildren,
  TrackOrderIdRoute: TrackOrderIdRoute,
  KategoriIndexRoute: KategoriIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
