INSERT INTO public.business_categories (
  slug,
  name,
  description,
  sort_order,
  is_active,
  enabled_features,
  flow_types,
  booking_enabled,
  booking_type,
  recommended_theme_key,
  subtypes
) VALUES
(
  'fnb',
  'F&B',
  'Warung, kafe, bakery, katering, dan usaha makanan minuman lainnya.',
  1,
  true,
  ARRAY['POS','MENU','KDS','TABLES','INVENTORY','VARIANTS','RECIPES','COMBO_BUILDER','ORDER_MODE']::text[],
  ARRAY['T1']::text[],
  false,
  null,
  'kuliner-warm',
  '[{"slug":"warung","label":"Warung"},{"slug":"kafe","label":"Kafe"},{"slug":"bakery","label":"Bakery"},{"slug":"katering","label":"Katering"}]'::jsonb
),
(
  'retail',
  'Retail',
  'Toko pakaian, sembako, aksesoris, elektronik, dan penjualan produk fisik.',
  2,
  true,
  ARRAY['POS','MENU','INVENTORY','VARIANTS','BUNDLES','PRODUCT_RETURNS','VARIANT_MATRIX']::text[],
  ARRAY['T1']::text[],
  false,
  null,
  'retail-bold',
  '[{"slug":"fashion","label":"Fashion"},{"slug":"sembako","label":"Sembako"},{"slug":"aksesoris","label":"Aksesoris"},{"slug":"elektronik","label":"Elektronik"}]'::jsonb
),
(
  'jasa',
  'Jasa',
  'Usaha jasa umum seperti servis, bengkel ringan, perbaikan, dan layanan profesional.',
  3,
  true,
  ARRAY['BOOKING','STAFF_PICKER','SERVICE_BUNDLES','FOLLOWUP_REMINDERS','CUSTOM_ORDER','CUSTOM_ORDER_QUOTES','MILESTONES','CONTRACTS','JOB_DELIVERABLES']::text[],
  ARRAY['T3','T5']::text[],
  true,
  'session',
  'service-clean',
  '[{"slug":"servis","label":"Servis"},{"slug":"konsultasi","label":"Konsultasi"},{"slug":"perbaikan","label":"Perbaikan"}]'::jsonb
),
(
  'rental',
  'Rental',
  'Sewa kendaraan, alat, perlengkapan acara, dan unit rental lainnya.',
  4,
  true,
  ARRAY['RENTAL','RENTAL_AVAILABILITY','RENTAL_DEPOSIT','RENTAL_FINES','RENTAL_CHECKLIST','RENTAL_TNC','RENTAL_EXTEND','RENTAL_UNIT_READY','RENTAL_KYC','RENTAL_INSPECTIONS']::text[],
  ARRAY['T4']::text[],
  true,
  'rental',
  'rental-bold',
  '[{"slug":"kendaraan","label":"Kendaraan"},{"slug":"alat","label":"Alat"},{"slug":"properti-acara","label":"Properti Acara"}]'::jsonb
),
(
  'kursus',
  'Kursus',
  'Kelas privat, bimbel, kursus online, dan pelatihan berjadwal.',
  5,
  true,
  ARRAY['BOOKING','STAFF_PICKER','SERVICE_BUNDLES','FOLLOWUP_REMINDERS','KURSUS','LESSON_PROGRESS','COURSE_CERTIFICATES','SESSION_MEMBERSHIP']::text[],
  ARRAY['T2','T3']::text[],
  true,
  'session',
  'course-bright',
  '[{"slug":"bimbel","label":"Bimbel"},{"slug":"kursus-online","label":"Kursus Online"},{"slug":"les-privat","label":"Les Privat"}]'::jsonb
),
(
  'salon',
  'Salon & Barbershop',
  'Salon kecantikan, barbershop, nail studio, dan treatment berjadwal.',
  6,
  true,
  ARRAY['BOOKING','STAFF_PICKER','SERVICE_BUNDLES','FOLLOWUP_REMINDERS','ANTRIAN','WAITLIST','CUSTOMER_TREATMENTS','SESSION_MEMBERSHIP']::text[],
  ARRAY['T3']::text[],
  true,
  'session',
  'beauty-soft',
  '[{"slug":"salon","label":"Salon"},{"slug":"barbershop","label":"Barbershop"},{"slug":"nail-art","label":"Nail Art"},{"slug":"spa","label":"Spa"}]'::jsonb
),
(
  'klinik',
  'Klinik',
  'Klinik umum, klinik kecantikan, praktik mandiri, dan layanan kesehatan.',
  7,
  true,
  ARRAY['BOOKING','STAFF_PICKER','ANTRIAN','WAITLIST','ANAMNESIS','MEDICAL_INVOICE','PATIENT_RECORDS','MEDICATIONS','PRESCRIPTIONS']::text[],
  ARRAY['T3']::text[],
  true,
  'session',
  'medical-clean',
  '[{"slug":"klinik-umum","label":"Klinik Umum"},{"slug":"klinik-kecantikan","label":"Klinik Kecantikan"},{"slug":"dokter-gigi","label":"Dokter Gigi"}]'::jsonb
),
(
  'studio-foto',
  'Studio Foto',
  'Studio foto keluarga, wisuda, produk, dan layanan dokumentasi.',
  8,
  true,
  ARRAY['BOOKING','SERVICE_BUNDLES','PORTFOLIO','STUDIO_PACKAGES','STUDIO_DELIVERY','STUDIO_BRIEF','STUDIO_ADDONS','STUDIO_GALLERY']::text[],
  ARRAY['T3']::text[],
  true,
  'session',
  'studio-editorial',
  '[{"slug":"foto-keluarga","label":"Foto Keluarga"},{"slug":"foto-produk","label":"Foto Produk"},{"slug":"wisuda","label":"Wisuda"}]'::jsonb
),
(
  'travel',
  'Travel',
  'Agen travel, tour, open trip, dan penjualan paket perjalanan.',
  9,
  true,
  ARRAY['UMROH_PACKAGES','UMROH_FACILITIES','UMROH_FAQ','FLYERS','TESTIMONIALS','LEADS','ABOUT_PAGE','TRAVEL_MANIFEST','TRAVEL_INSTALLMENTS','TRAVEL_ITINERARY','JAMAAH_DOCUMENTS']::text[],
  ARRAY['T1']::text[],
  false,
  null,
  'travel-vivid',
  '[{"slug":"open-trip","label":"Open Trip"},{"slug":"tour","label":"Tour"},{"slug":"umroh","label":"Umroh"}]'::jsonb
),
(
  'custom-order',
  'Custom Order',
  'Produksi by order, jasa desain, percetakan, dan pesanan sesuai brief.',
  10,
  true,
  ARRAY['CUSTOM_ORDER','CUSTOM_ORDER_QUOTES','MILESTONES','CONTRACTS','JOB_DELIVERABLES','PRE_ORDERS']::text[],
  ARRAY['T5']::text[],
  false,
  null,
  'custom-craft',
  '[{"slug":"desain","label":"Desain"},{"slug":"percetakan","label":"Percetakan"},{"slug":"produksi","label":"Produksi"}]'::jsonb
),
(
  'lainnya',
  'Lainnya',
  'Kategori umum untuk usaha yang belum masuk kategori khusus.',
  11,
  true,
  ARRAY['POS','MENU','BOOKING','CUSTOM_ORDER']::text[],
  ARRAY['T1','T3','T5']::text[],
  false,
  null,
  'generic-flex',
  '[]'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active,
  enabled_features = EXCLUDED.enabled_features,
  flow_types = EXCLUDED.flow_types,
  booking_enabled = EXCLUDED.booking_enabled,
  booking_type = EXCLUDED.booking_type,
  recommended_theme_key = EXCLUDED.recommended_theme_key,
  subtypes = EXCLUDED.subtypes,
  updated_at = now();